app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

					Route::get('/', 'GuestController@index');
					Route::get('auth/verify/{token}','Auth\AuthController@verify');	
					Route::get('auth/send-verification','Auth\AuthController@resend');


					Route::auth();
					Route::get('/home','HomeController@index');
					Route::get('setting/profile','SettingController@profile');
					Route::get('setting/profile/edit','SettingController@setProfile');
					Route::post('setting/profile','SettingController@updateProfile');
					Route::get('setting/changepassword','SettingController@editPassword');
					Route::post('setting/password','SettingController@updatePassword');
					Route::get('book/{id}/borrow', ['middleware'=>['auth','role:member'],
													'as'		=> 'book.borrow',
													'uses'		=> 'BookController@borrow']);
					Route::put('book/{id}/return',['middleware'=>['auth','role:member'],
													'as'	   => 'book.return',
													'uses'     => 'BookController@returnBack']);
					Route::group(['prefix'=>'admin','middleware'=>['auth','role:admin']],function(){

							Route::resource('authors','AuthorController');
							Route::resource('books','BookController');
					});

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    //

	protected $fillable = ['title','amount','author_id','cover'];
    public $timestamps = false;

    public static function boot(){
    	parent::boot();
    	self::updating(function($book){
    			if($book -> amount < $book->borrowed){
    				 Session::flash("flash_notification",[
					                "level"=>'danger',
					                "message"=>"Amount Book ". $book->title . " must more than or equals ".$book->borrowed]);
    				 return false;
    			}
    	});
    	self::deleting(function($book){
    		if ($book->borrowLogs()->borrowed()->count() > 0) {
    			 Session::flash("flash_notification",[
					                "level"=>'danger',
					                "message"=>"Books Already borrowed or Books Borrowed "]);
    				 return false;
    		}
    	});
    }

    public function hasAuthor(){
    	return $this->belongsTo('App\Author','author_id');
    }
    public function borrowLogs(){
    	return $this->hasMany('App\BorrowLog');
    }
    public function getBorrowedAttribute(){
    	return $this->borrowLogs()->borrowed()->count();
    }
    public function getStockAttribute(){
     	///method borrowlogs -> scope di borrowlogs -> count function
     	$borrowed = $this->borrowLogs()->borrowed()->count();
     	$stock = $this->amount - $borrowed;
     	return $stock;   
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use File;
use App\Http\Requests;
use App\Book;
use Session;
use App\Http\Requests\StoreBookRequest;
use App\Http\Requests\UpdateBookRequest;
use Auth;
use App\BorrowLog;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use App\Exceptions\BookException;

class BookController extends Controller
{
    
    public function index()
    {
        //
        $books = Book::with('hasAuthor')->orderBy('id','DESC')->get();
        return View('book.index',compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        return View('book.create'); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBookRequest $request)
    {
        //

        $book = Book::create($request->except('cover'));

        if($request->hasFile('cover')){
            $uploadedCover = $request->file('cover');
            $extension = $uploadedCover->getClientOriginalExtension();
            $fileName = rand(1,1000)."_".date('Y-m-d').".".$extension;
            $path = public_path(). DIRECTORY_SEPARATOR . 'img';
            $uploadedCover->move($path,$fileName);
            $book->cover =  $fileName;
            $book->save();

        }
         Session::flash("flash_notification",[
                "level"=>'success',
                "message"=>"Add ". $book->title . " Success"]);

        return Redirect('admin/books');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $book = Book::findOrfail($id);
        return View('book.edit',compact('book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBookRequest $request, $id)
    {
        //
   
        $book = Book::findOrfail($id);
        $data = $request->only('title','author_id','amount');
        if(!$book->update($request->all())) return redirect()->back();
         if($request->hasFile('cover') == true){
            $path = public_path(). DIRECTORY_SEPARATOR . 'img';
            File::delete($path.DIRECTORY_SEPARATOR.$book->cover);
            $uploadedCover = $request->file('cover');
            $extension = $uploadedCover->getClientOriginalExtension();
            $fileName = rand(1,1000)."_".date('Y-m-d').".".$extension;
            $uploadedCover->move($path,$fileName);    
            $data['cover']=$fileName;
        }

        $book->update($data);
        Session::flash("flash_notification",[
                "level"=>'success',
                "message"=>"Update ". $book->title . " Success"]);
        return Redirect('admin/books');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $book = Book::findOrfail($id);
        if(!$book->delete()) return Redirect()->back();
        if($book->cover !==''){
            $path = public_path(). DIRECTORY_SEPARATOR . 'img';

            File::delete($path.DIRECTORY_SEPARATOR.$book->cover);
        }
        $book -> delete();
        Session::flash("flash_notification",[
                "level"=>'success',
                "message"=>"Delete Success"]);
        return Redirect('admin/books');


    }
    public function borrow($id){

        try {
                $book = Book::findOrfail($id);
                Auth::user()->borrow($book);
                Session::flash("flash_notification",[
                "level"=>'success',
                "message"=>"Borrow ".$book->title." Success"]);

        }catch (BookException $e){
                 Session::flash("flash_notification",[
                "level"=>'danger',
                "message"=>$e->getMessage()]);
        } 
        catch (ModelNotFoundException $e) {
                Session::flash("flash_notification",[
                "level"=>'danger',
                "message"=>"Book Not Found"]);
            
        }
        return Redirect('/');
    }

    public function returnBack($id){
        $BorrowLog = BorrowLog::where('user_id',Auth::user()->id)
                                ->where('book_id',$id)
                                ->where('is_returned',0)
                                ->first();
        if($BorrowLog){
            $BorrowLog -> is_returned = true;
            $BorrowLog ->  save();
             Session::flash("flash_notification",[
                "level"=>'success',
                "message"=>"Return ".$BorrowLog->book->title." Success"]);
        }
        return Redirect('/home');
    }
}

resources/views/book/_form.blade.php
<div class="form-group {{$errors->has('title') ? 'has-error' : ''}}">
	{{Form::label('title','Title',['class'=>'col-md-2 control-label'])}}
	<div class="col-md-4">
		{{Form::text('title',null,['class'=>'form-control'])}}
		{!!$errors->first('title','<p class="help-block"><strong>:message</strong> </p>') !!}
	</div>
</div>
<div class="form-group {{$errors->has('author_id') ? 'has-error' : ''}}">
	{{Form::label('author','Author',['class'=>'col-md-2 control-label'])}}
	<div class="col-md-4">
		{{Form::select('author_id',[''=>'']+App\Author::pluck('name','id')->all(),null,['id'=>'select-beast'])}}
		{!!$errors->first('author_id','<p class="help-block"><strong>:message</strong> </p>') !!}
	</div>
</div>
<div class="form-group {{$errors->has('amount') ? 'has-error' : ''}}">
	{{Form::label('amount','Jumlah',['class'=>'col-md-2 control-label'])}}
	<div class="col-md-4">
		{{Form::number('amount',null,['class'=>'form-control','min'=>1])}}
		{!!$errors->first('amount','<p class="help-block"><strong>:message</strong> </p>') !!}
		@if(isset($model))
			<span class="help-block">
				<strong>{{$model->borrowed}} Borrowed</strong>
			</span>
		@endif
	</div>
</div>
<div class="form-group {{$errors->has('cover') ? 'has-error' : ''}}">
	{{Form::label('cover','cover',['class'=>'col-md-2 control-label'])}}
	<div class="col-md-4">

		{{Form::file('cover')}}
		{!!$errors->first('cover','<p class="help-block"><strong>:message</strong> </p>') !!}
		@if(isset($model))
		<img src="{{asset('img')}}/{{$model->cover}}" alt="">
		@endif
	</div>
</div>
<div class="form-group">
	<div class="col-md-4 col-md-offset-2">
			{{Form::submit(isset($model) ? 'Update' : 'Save' , ['class'=>'btn btn-info'])}}
	</div>
</div>

resources/views/book/create.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{url('/home')}}">Dashboard</a></li>
					<li><a href="{{url('/admin/books')}}">Books</a></li>
					<li class="active">Add book</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Add book</h2>
					</div>
				</div>
				<div class="panel-body">
					{{Form::open(['url'=>route('admin.books.store'),'method'=>'post','files'=>true,'class'=>'form-horizontal'])}}					
							@include('book._form')
					{{Form::close()}}
				</div>
			</div>
		</div>
	</div>

@endsection

resources/views/book/edit.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{url('/home')}}">Dashboard</a></li>
					<li><a href="{{url('/admin/books')}}">Books</a></li>
					<li class="active">Edit book</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Edit book</h2>
					</div>
				</div>
				<div class="panel-body">
					{{Form::model($book,['url'=>route('admin.books.update',$book->id),'method'=>'put','files'=>true,'class'=>'form-horizontal'])}}					
							@include('book._form',['model'=>$book])
					{{Form::close()}}
				</div>
			</div>
		</div>
	</div>

@endsection

resources/views/book/index.blade.php
@extends('layouts.app')
@section('content')

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{url('/home')}}">Dashboard</a></li>
					<li class="active">Books</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Books</h2>
					</div>
				</div>
				<div class="panel-body">
					<p><a href="{{Url('admin/books/create')}}" class="btn btn-success">Add Books</a></p>
					<table class="table table-stripped" id="dataTable">
						<thead>
							<tr>
								<th>No</th>
								<th>Book Title</th>
								<th>Author</th>
								<th>Amount</th>
								<th>Action</th>
							</tr>
						</thead>
						@php($no=1)
						<tbody>
							@foreach($books as $data)
							<tr>
								<td>{{$no++}}</td>
								<td>{{$data->title}}</td>
								<td>{{$data->hasAuthor->name}}</td>
								<td>{{$data->amount}}</td>
								<td>
									{{Form::model($data,['route'=>['admin.books.destroy',$data],'method'=>'delete','class'=>'form-inline','onsubmit'=>'return confirm("Are you Sure ?")'])}}
									<a href="{{url('admin/books')}}/{{$data->id}}/edit" class="btn btn-success">Edit</a>
									{{Form::submit('Delete',['class'=>'btn btn-danger'])}}
									{{Form::close()}}
								</td>


							</tr>
							@endforeach
						</tbody>
						
					</table>
				</div>
			</div>
		</div>
	</div>


@endsection