app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

					Route::get('/', 'GuestController@index');
					Route::get('auth/verify/{token}','Auth\AuthController@verify');	
					Route::get('auth/send-verification','Auth\AuthController@resend');


					Route::auth();
					Route::get('/home','HomeController@index');
					Route::get('setting/profile','SettingController@profile');
					Route::get('setting/profile/edit','SettingController@setProfile');
					Route::post('setting/profile','SettingController@updateProfile');
					Route::get('setting/changepassword','SettingController@editPassword');
					Route::post('setting/password','SettingController@updatePassword');
					Route::get('book/{id}/borrow', ['middleware'=>['auth','role:member'],
													'as'		=> 'book.borrow',
													'uses'		=> 'BookController@borrow']);
					Route::put('book/{id}/return',['middleware'=>['auth','role:member'],
													'as'	   => 'book.return',
													'uses'     => 'BookController@returnBack']);
					Route::group(['prefix'=>'admin','middleware'=>['auth','role:admin']],function(){

							Route::resource('authors','AuthorController');
							Route::resource('books','BookController');
					});

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    //
    protected $fillable = ['name'];

    public function hasBooks(){
    	return $this->hasMany('App\Book');
    }
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Author;
use Session;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $rules = ['name'=>'required|min:6'];

    public function index()
    {
        //
        $authors = Author::select(['name','id'])->get();

        return View('author.index',compact('authors'));

        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return View('author.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,$this->rules);

      $author = Author::create($request->all());
        Session::flash("flash_notification",[
                "level"=>'success',
                "message"=>"Add ". $author->name . " Success"]);

        return Redirect('admin/authors');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $author = Author::findOrfail($id);
        return View('author.edit',compact('author'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,$this->rules);
        $author = Author::findOrfail($id);
        $author->update($request->all());
        Session::flash("flash_notification",[
                "level"=>'success',
                "message"=>"Update ". $author->name . " Success"]);
        return Redirect('admin/authors');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $author= Author::findOrfail($id);

        $author->delete();
         Session::flash("flash_notification",[
                "level"=>'danger',
                "message"=>"Delete Success"]);
        return Redirect('admin/authors');
    }
}

resources/views/author/_form.blade.php
	<div class="form-group {{$errors->has('name') ? 'has-error' : ''}}">
			<label for="" class="col-md-2 control-label">
				Nama
			</label>
			<div class="col-md-4">
				{{Form::text('name',null,['class'=>'form-control'])}}
				{!!$errors->first('name','<p class="help-block">:message</p>')!!}
			</div>
	</div>

	<div class="form-group {{$errors->has('name') ? 'has-error' : ''}}">
			<div class="col-md-4 col-md-offset-2">
				{{Form::submit(isset($model) ? 'Edit' :'Add' ,['class'=>'btn btn-primary'])}}
			</div>
	</div>

resources/views/author/create.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{url('/home')}}">Dashboard</a></li>
					<li><a href="{{url('/admin/authors')}}">Penulis</a></li>
					<li class="active">Add Authors</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Add Authors</h2>
					</div>
				</div>
				<div class="panel-body">
					{{Form::open(['url'=>route('admin.authors.store'),'method'=>'post','class'=>'form-horizontal'])}}					
							@include('author._form')
					{{Form::close()}}
				</div>
			</div>
		</div>
	</div>

@endsection

resources/views/author/edit.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{url('/home')}}">Dashboard</a></li>
					<li><a href="{{url('/admin/authors')}}">Penulis</a></li>
					<li class="active">Edit Authors</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Edit Authors</h2>
					</div>
				</div>
				<div class="panel-body">
					{{Form::model($author,['url'=>route('admin.authors.update',$author->id),'method'=>'put','class'=>'form-horizontal'])}}					
							@include('author._form',['model'=>$author])
					{{Form::close()}}
				</div>
			</div>
		</div>
	</div>

@endsection

resources/views/author/index.blade.php
@extends('layouts.app')
@section('content')

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{url('/home')}}">Dashboard</a></li>
					<li class="active">Penulis</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Penulis</h2>
					</div>
				</div>
				<div class="panel-body">
					<p><a href="{{Url('admin/authors/create')}}" class="btn btn-success">Add Authors</a></p>
					<table class="table table-stripped" id="dataTable">
						<thead>
							<tr>
								<th>No</th>
								<th>Nama</th>
								<th>Action</th>
							</tr>
						</thead>
						@php($no=1)
						<tbody>
							@foreach($authors as $data)
							<tr>
								<td>{{$no++}}</td>
								<td>{{$data->name}}</td>
								<td>
									{{Form::model($data,['route'=>['admin.authors.destroy',$data],'method'=>'delete','class'=>'form-inline','onsubmit'=>'return confirm("Are you Sure ?")'])}}
									<a href="{{url('admin/authors')}}/{{$data->id}}/edit" class="btn btn-success">Edit</a>
									{{Form::submit('Delete',['class'=>'btn btn-danger'])}}
									{{Form::close()}}
								</td>


							</tr>
							@endforeach
						</tbody>
						
					</table>
				</div>
			</div>
		</div>
	</div>


@endsection